package:
  name: bimtree
  version: 2020-03-09a0.dev0

source:
  fn: bimtree-2020-03-09a0.dev0.tar.gz
  url: https://github.com/salotz/bimtree/releases/download//{{ version }}/{{ name }}-{{ version }}.tar.gz
  # TODO: way to specify a hole or 
  sha256:

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - bimtree = bimtree.cli:cli

requirements:
  build:
    - python
    - setuptools
    - wheel

  host:
    - python
    
  run:
    - python
    

about:
  home: https://github.com/salotz/bimtree
  license: MIT
  license_file: LICENSE
  summary: "Initialize and manage knowledge-work domains"
  doc_url: https://salotz.github.io/bimtree
  dev_url: https://github.com/salotz/bimtree

extra:
  recipe-maintainers:
    - salotz
